# Generated by Django 4.0.3 on 2022-04-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='description',
            new_name='backDescription',
        ),
        migrations.AddField(
            model_name='card',
            name='frontDescription',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='card',
            name='has_back',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
