# Generated by Django 4.0.3 on 2022-04-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_description_card_backdescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='occasion',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
