# Generated by Django 4.0.3 on 2022-04-09 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_following_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='has_back',
            field=models.CharField(default='false', max_length=10),
        ),
        migrations.AlterField(
            model_name='card',
            name='liked',
            field=models.CharField(default='false', max_length=10),
        ),
        migrations.AlterField(
            model_name='card',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card', to=settings.AUTH_USER_MODEL),
        ),
    ]
