# Generated by Django 4.0.3 on 2022-04-10 00:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_card_has_back_alter_card_liked_alter_card_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='Users', to=settings.AUTH_USER_MODEL),
        ),
    ]
