# Generated by Django 4.0.3 on 2022-04-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_card_liked_card_like_alter_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='Card_Alignment',
            field=models.CharField(blank=True, choices=[('Start', 'Start'), ('End', 'End'), ('Flex-Start', 'Flex-Start'), ('Flex-End', 'Flex-End'), ('Center', 'Center'), ('Left', 'Left'), ('Right', 'Right'), ('Normal', 'Normal'), ('Space-Between', 'Space-Between'), ('Space-Around', 'Space-Around'), ('Space-Evenly', 'Space-Evenly'), ('Stretch', 'Stretch'), ('Safe', 'Safe'), ('Unsafe', 'Unsafe')], max_length=200),
        ),
        migrations.AddField(
            model_name='card',
            name='card_font',
            field=models.CharField(blank=True, choices=[('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato'), ('Oswald', 'Oswald'), ('Concert One', 'Concert One')], max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='backDescription',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
