# Generated by Django 4.0.3 on 2022-04-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_card_card_alignment_card_card_font_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='Card_Alignment',
            new_name='card_alignment',
        ),
    ]
