# Generated by Django 4.0.3 on 2022-04-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_card_alignment_card_card_alignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='frontDescription',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='card',
            name='occasion',
            field=models.CharField(max_length=50),
        ),
    ]
