# Generated by Django 4.0.3 on 2022-04-12 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_card_frontdescription_alter_card_occasion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion', models.CharField(max_length=50)),
                ('frontDescription', models.CharField(max_length=250)),
                ('backDescription', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('profile_pic', models.URLField(blank=True, max_length=500)),
                ('has_back', models.CharField(default='false', max_length=10)),
                ('card_alignment', models.CharField(blank=True, choices=[('Start', 'Start'), ('End', 'End'), ('Flex-Start', 'Flex-Start'), ('Flex-End', 'Flex-End'), ('Center', 'Center'), ('Left', 'Left'), ('Right', 'Right'), ('Normal', 'Normal'), ('Space-Between', 'Space-Between'), ('Space-Around', 'Space-Around'), ('Space-Evenly', 'Space-Evenly'), ('Stretch', 'Stretch'), ('Safe', 'Safe'), ('Unsafe', 'Unsafe')], max_length=200)),
                ('card_font', models.CharField(blank=True, choices=[('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato'), ('Oswald', 'Oswald'), ('Concert One', 'Concert One')], max_length=200)),
                ('card_color', models.CharField(blank=True, choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Violet', 'Violet')], max_length=200)),
                ('border', models.CharField(blank=True, choices=[('Beaded', 'Beaded'), ('Chain Link', 'Chain Link'), ('Subtle Triple', 'Subtle Triple')], max_length=200)),
                ('like', models.ManyToManyField(blank=True, related_name='draft_user_like', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_card', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
