# Generated by Django 4.0.3 on 2022-04-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_profilemodel_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='font_color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('Red', 'Red'), ('White', 'White'), ('Gray', 'Gray'), ('Yellow', 'Yellow'), ('Silver', 'Silver')], max_length=200),
        ),
    ]
